---

- name: VLAN COUNT ON Juniper JunOS SWITCH
  hosts: l2ios
  gather_facts: no
  connection: network_cli
  vars:
    - result_dir: ./results/
  tasks:

  - name: remove local files
    file: 
      path: "{{ item }}"
      state: absent
    loop:
      - "{{ result_dir }}customer_vlan.json"
      - "{{ result_dir }}total_vlan.json"
      - "{{ result_dir }}total_voice_vlan.json"
      - "{{ result_dir }}customer_voice_vlan.json"
    run_once: true

  - name: read lookup variables from file
    include_vars: 
      file: ./files/lookup.txt
      name: lookup
    run_once: true

  - name: gather interface facts
    junipernetworks.junos.junos_facts:
      gather_network_resources: 
            - l2_interfaces
    become: true
    register: _intf_facts

  - set_fact:
      _l2_interfaces: "{{ _intf_facts.ansible_facts.ansible_network_resources }}"
    
  - set_fact:  
      _vlan_ids: "{{ _l2_interfaces | json_query('l2_interfaces[*].access.vlan')  }}"
      _voice_vlan_ids:  "{{ _l2_interfaces | json_query('l2_interfaces[*].voice.vlan')  }}"
  
  - name: VLAN IDs
    debug:
      var: _vlan_ids
  
  - name: VOICE VLAN IDs
    debug:
      var: _voice_vlan_ids

  - name: generate total VLAN reports
    template: 
      src: "./templates/{{ item }}.j2"
      dest: "{{ result_dir }}{{ item }}.json"
    delegate_to: localhost
    run_once: true
    loop: 
      - total_vlan
      - total_voice_vlan
  
  - name: read total VLAN infos
    include_vars: 
      file: "{{ result_dir }}{{ item }}.json"
      name: "{{ item }}_result"
    run_once: true
    loop: 
      - total_vlan
      - total_voice_vlan

  - name: generate customer VLAN report
    template: 
      src: ./templates/customer_vlan.j2
      dest: "{{ result_dir }}customer_vlan.json"
    delegate_to: localhost
    run_once: true

  - set_fact:
      total_vlan_result: "{{ total_voice_vlan_result }}"
  
  - name: generate customer VOICE VLAN report
    template: 
      src: ./templates/customer_vlan.j2
      dest: "{{ result_dir }}customer_voice_vlan.json"
    delegate_to: localhost
    run_once: true
